version: "3.9"
services:
  db:
    image: postgres:15
    container_name: user-crud-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: user-crud-app
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=db_password
      - DB_NAME=users_db
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgresql://postgres:db_password@db:5432/users_db
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata:
