# Development Dockerfile
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npx prisma generate

COPY . .

# Use ts-node-dev for hot-reloading
RUN npm install -g ts-node-dev

EXPOSE 3000
CMD ["ts-node-dev", "--respawn", "src/app.ts"]
